export const team = [
  {
    id: 1,
    name: "Ahmed Hassan",
    role: "Chief Security Officer",
    expertise: "Ethical Hacking, Penetration Testing, Network Security",
    certifications: ["CEH", "OSCP", "GPEN"],
    bio: "15+ years of cybersecurity experience. Led security teams for Fortune 500 companies.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
  },
  {
    id: 2,
    name: "Fatima Khan",
    role: "Senior Penetration Tester",
    expertise: "Web Application Security, API Testing, OWASP",
    certifications: ["OSCP", "eWPT", "CEH"],
    bio: "Bug bounty hunter with over 200 vulnerabilities found. Expert in web security.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
  },
  {
    id: 3,
    name: "Ali Raza",
    role: "SOC Manager",
    expertise: "Incident Response, SIEM, Threat Intelligence",
    certifications: ["GCIA", "GCIH", "ACP"],
    bio: "Expert in building and managing Security Operations Centers. 10+ years experience.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
  },
  {
    id: 4,
    name: "Hina Memon",
    role: "Security Researcher",
    expertise: "Vulnerability Research, OSINT, Bug Bounty",
    certifications: ["CEH", "eJPT"],
    bio: "QUEST University student. CTF champion with expertise in security research.",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
  },
];

export const certifications = [
  {
    name: "CEH",
    fullName: "Certified Ethical Hacker",
    issuer: "EC-Council",
    color: "#e63946",
    logo: "/ceh-badge.png",
  },
  {
    name: "OSCP",
    fullName: "Offensive Security Certified Professional",
    issuer: "Offensive Security",
    color: "#1a4a7a",
    logo: "/oscp-badge.png",
  },
  {
    name: "GPEN",
    fullName: "GIAC Penetration Tester",
    issuer: "GIAC / SANS Institute",
    color: "#2a5c8a",
    logo: "/gpen-badge.png",
  },
  {
    name: "eWPT",
    fullName: "eLearnSecurity Web App Pentester",
    issuer: "INE Security",
    color: "#1a6cc4",
    logo: "https://logo.clearbit.com/ine.com",
  },
  {
    name: "ISO 27001",
    fullName: "Information Security Management",
    issuer: "ISO / IEC",
    color: "#7c3aed",
    logo: "https://logo.clearbit.com/iso.org",
  },
];
